var hierarchy =
[
    [ "AudioOutput", "class_primo_software_1_1_burner_1_1_audio_output.html", null ],
    [ "BDFeatures", "class_primo_software_1_1_burner_1_1_b_d_features.html", null ],
    [ "BDFormatParameters", "class_primo_software_1_1_burner_1_1_b_d_format_parameters.html", null ],
    [ "BDMediaInfo", "class_primo_software_1_1_burner_1_1_b_d_media_info.html", null ],
    [ "BDVersion", "class_primo_software_1_1_burner_1_1_b_d_version.html", null ],
    [ "BootProps", "class_primo_software_1_1_burner_1_1_boot_props.html", null ],
    [ "CachePolicy", "class_primo_software_1_1_burner_1_1_cache_policy.html", null ],
    [ "CDFeatures", "class_primo_software_1_1_burner_1_1_c_d_features.html", null ],
    [ "CDMode", "class_primo_software_1_1_burner_1_1_c_d_mode.html", null ],
    [ "CDPregap", "struct_primo_software_1_1_burner_1_1_c_d_pregap.html", null ],
    [ "CDSector", "class_primo_software_1_1_burner_1_1_c_d_sector.html", null ],
    [ "CDSession", "class_primo_software_1_1_burner_1_1_c_d_session.html", null ],
    [ "CDText", "class_primo_software_1_1_burner_1_1_c_d_text.html", null ],
    [ "CDTextItem", "class_primo_software_1_1_burner_1_1_c_d_text_item.html", null ],
    [ "CDTrack", "class_primo_software_1_1_burner_1_1_c_d_track.html", null ],
    [ "DataFile", "class_primo_software_1_1_burner_1_1_data_file.html", null ],
    [ "DiscArchive", "class_primo_software_1_1_burner_1_1_disc_archive.html", null ],
    [ "DiscCopy", "class_primo_software_1_1_burner_1_1_disc_copy.html", null ],
    [ "DiscInfo", "class_primo_software_1_1_burner_1_1_disc_info.html", null ],
    [ "DVDFeatures", "class_primo_software_1_1_burner_1_1_d_v_d_features.html", null ],
    [ "DVDMediaInfo", "class_primo_software_1_1_burner_1_1_d_v_d_media_info.html", null ],
    [ "DVDMinusMediaInfo", "class_primo_software_1_1_burner_1_1_d_v_d_minus_media_info.html", null ],
    [ "DVDPlusMediaInfo", "class_primo_software_1_1_burner_1_1_d_v_d_plus_media_info.html", null ],
    [ "EventArgs", null, [
      [ "AudioCDContinueEventArgs", "class_primo_software_1_1_burner_1_1_audio_c_d_continue_event_args.html", null ],
      [ "AudioCDProgressEventArgs", "class_primo_software_1_1_burner_1_1_audio_c_d_progress_event_args.html", null ],
      [ "AudioCDStatusEventArgs", "class_primo_software_1_1_burner_1_1_audio_c_d_status_event_args.html", null ],
      [ "AudioCDTrackStatusEventArgs", "class_primo_software_1_1_burner_1_1_audio_c_d_track_status_event_args.html", null ],
      [ "DataDiscContinueEventArgs", "class_primo_software_1_1_burner_1_1_data_disc_continue_event_args.html", null ],
      [ "DataDiscFileStatusEventArgs", "class_primo_software_1_1_burner_1_1_data_disc_file_status_event_args.html", null ],
      [ "DataDiscProgressEventArgs", "class_primo_software_1_1_burner_1_1_data_disc_progress_event_args.html", null ],
      [ "DataDiscStatusEventArgs", "class_primo_software_1_1_burner_1_1_data_disc_status_event_args.html", null ],
      [ "DeviceContinueEventArgs", "class_primo_software_1_1_burner_1_1_device_continue_event_args.html", null ],
      [ "DeviceEraseEventArgs", "class_primo_software_1_1_burner_1_1_device_erase_event_args.html", null ],
      [ "DeviceFormatEventArgs", "class_primo_software_1_1_burner_1_1_device_format_event_args.html", null ],
      [ "DeviceReadEventArgs", "class_primo_software_1_1_burner_1_1_device_read_event_args.html", null ],
      [ "DeviceWriteLeadInEventArgs", "class_primo_software_1_1_burner_1_1_device_write_lead_in_event_args.html", null ],
      [ "DeviceWriteLeadOutEventArgs", "class_primo_software_1_1_burner_1_1_device_write_lead_out_event_args.html", null ],
      [ "DiscArchiveAddFileToLayoutEventArgs", "class_primo_software_1_1_burner_1_1_disc_archive_add_file_to_layout_event_args.html", null ],
      [ "DiscArchiveFileErrorEventArgs", "class_primo_software_1_1_burner_1_1_disc_archive_file_error_event_args.html", null ],
      [ "DiscArchiveFooterSizeEventArgs", "class_primo_software_1_1_burner_1_1_disc_archive_footer_size_event_args.html", null ],
      [ "DiscArchiveRequestRenameEventArgs", "class_primo_software_1_1_burner_1_1_disc_archive_request_rename_event_args.html", null ],
      [ "DiscCopyContinueCopyEventArgs", "class_primo_software_1_1_burner_1_1_disc_copy_continue_copy_event_args.html", null ],
      [ "DiscCopyProgressEventArgs", "class_primo_software_1_1_burner_1_1_disc_copy_progress_event_args.html", null ],
      [ "DiscCopyStatusEventArgs", "class_primo_software_1_1_burner_1_1_disc_copy_status_event_args.html", null ],
      [ "DiscCopyTrackStatusEventArgs", "class_primo_software_1_1_burner_1_1_disc_copy_track_status_event_args.html", null ],
      [ "DiscLayoutContinueWriteEventArgs", "class_primo_software_1_1_burner_1_1_disc_layout_continue_write_event_args.html", null ],
      [ "DiscLayoutFileErrorEventArgs", "class_primo_software_1_1_burner_1_1_disc_layout_file_error_event_args.html", null ],
      [ "DiscLayoutFileEventArgs", "class_primo_software_1_1_burner_1_1_disc_layout_file_event_args.html", null ],
      [ "DiscLayoutProgressEventArgs", "class_primo_software_1_1_burner_1_1_disc_layout_progress_event_args.html", null ],
      [ "EngineDeviceChangeEventArgs", "class_primo_software_1_1_burner_1_1_engine_device_change_event_args.html", null ],
      [ "EngineMediaChangeEventArgs", "class_primo_software_1_1_burner_1_1_engine_media_change_event_args.html", null ]
    ] ],
    [ "GenericError", "struct_primo_software_1_1_burner_1_1_generic_error.html", null ],
    [ "ICloneable", null, [
      [ "AudioInput", "class_primo_software_1_1_burner_1_1_audio_input.html", null ],
      [ "ErrorInfo", "class_primo_software_1_1_burner_1_1_error_info.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "AudioCD", "class_primo_software_1_1_burner_1_1_audio_c_d.html", null ],
      [ "BlockDevice", "class_primo_software_1_1_burner_1_1_block_device.html", null ],
      [ "DataDisc", "class_primo_software_1_1_burner_1_1_data_disc.html", null ],
      [ "Device", "class_primo_software_1_1_burner_1_1_device.html", null ],
      [ "DeviceEnumerator", "class_primo_software_1_1_burner_1_1_device_enumerator.html", null ],
      [ "DiscLayout", "class_primo_software_1_1_burner_1_1_disc_layout.html", null ],
      [ "Engine", "class_primo_software_1_1_burner_1_1_engine.html", null ],
      [ "ScsiInterface", "class_primo_software_1_1_burner_1_1_scsi_interface.html", null ],
      [ "VideoDVD", "class_primo_software_1_1_burner_1_1_video_d_v_d.html", null ]
    ] ],
    [ "IEnumerable< DataFile >", null, [
      [ "DataFileList", "class_primo_software_1_1_burner_1_1_data_file_list.html", null ]
    ] ],
    [ "IsoVolumeProps", "class_primo_software_1_1_burner_1_1_iso_volume_props.html", null ],
    [ "JolietVolumeProps", "class_primo_software_1_1_burner_1_1_joliet_volume_props.html", null ],
    [ "Library", "class_primo_software_1_1_burner_1_1_library.html", null ],
    [ "MediaInfo", "class_primo_software_1_1_burner_1_1_media_info.html", null ],
    [ "Mode2FormedSubheader", "struct_primo_software_1_1_burner_1_1_mode2_formed_subheader.html", null ],
    [ "PCMAudioFormat", "struct_primo_software_1_1_burner_1_1_p_c_m_audio_format.html", null ],
    [ "QSubChannel", "class_primo_software_1_1_burner_1_1_q_sub_channel.html", null ],
    [ "QSubChannelIsrc", "class_primo_software_1_1_burner_1_1_q_sub_channel_isrc.html", null ],
    [ "QSubChannelMcn", "class_primo_software_1_1_burner_1_1_q_sub_channel_mcn.html", null ],
    [ "QSubChannelPosition", "class_primo_software_1_1_burner_1_1_q_sub_channel_position.html", null ],
    [ "RawToc", "class_primo_software_1_1_burner_1_1_raw_toc.html", null ],
    [ "RawTocTrack", "class_primo_software_1_1_burner_1_1_raw_toc_track.html", null ],
    [ "ScsiCommandSense", "class_primo_software_1_1_burner_1_1_scsi_command_sense.html", null ],
    [ "SessionInfo", "class_primo_software_1_1_burner_1_1_session_info.html", null ],
    [ "Speed1xKB", "struct_primo_software_1_1_burner_1_1_speed1x_k_b.html", null ],
    [ "SpeedDescriptor", "class_primo_software_1_1_burner_1_1_speed_descriptor.html", null ],
    [ "Toc", "class_primo_software_1_1_burner_1_1_toc.html", null ],
    [ "TocTrack", "class_primo_software_1_1_burner_1_1_toc_track.html", null ],
    [ "TrackBuffer", "class_primo_software_1_1_burner_1_1_track_buffer.html", null ],
    [ "TrackInfo", "class_primo_software_1_1_burner_1_1_track_info.html", null ],
    [ "TrackInfoEx", "class_primo_software_1_1_burner_1_1_track_info_ex.html", null ],
    [ "UdfExtent", "class_primo_software_1_1_burner_1_1_udf_extent.html", null ],
    [ "UdfFileProps", "class_primo_software_1_1_burner_1_1_udf_file_props.html", null ],
    [ "UdfVolumeProps", "class_primo_software_1_1_burner_1_1_udf_volume_props.html", null ]
];