PrimoBurner(tm) for C++: PrimoBurnerAPI.h File Reference
PrimoBurnerAPI.h File Reference
Classes
class AudioCD
Burns and rips audio CDs from/to audio files.
class AudioCDCallback
Implement this interface to receive progress notifications from AudioCD when writing or reading audio.
class AudioInput
Defines an audio input for Audio CD writing.
class AudioInputList
Represents a list of AudioInput objects.
class AudioOutput
Defines an audio output when reading from an Audio CD.
class BDFeatures
Serves as a container for the Blu-ray Disc features supported by the device.
class BDFormatParameters
Reserved for future versions.
class BDMediaInfo
Container for BD-R and BD-RE media information.
class BDVersion
Serves as a container for BD class and BD version information.
class BDVersionEnum
Enumerator for Blu-ray Disc Version objects.
class BlockDevice
BlockDevice provides methods for reading and writing data CD, DVD and BD in packet mode.
class BootProps
Provides an interface for setting the properties of a bootable disc.
class CachePolicy
Provides an interface for setting the cache related properties of DataDisc.
class CDFeatures
Container for the CD features supported by the device.
class CDIndexList
Represents a collection of CD track indexes.
class CDMode
The CDMode class defines a point at which the type and/or the frame size of a CD track changes.
class CDModeList
Represents a list of CDMode objects.
class CDSector
The CDSector interface provides methods that allow encoding of RAW CD blocks from user data.
class CDSession
The CDSession interface defines the layout (the TOC) of a CD session.
class CDText
The CDText interface is used to manipulate the CD-TEXT data of an audio CD.
class CDTrack
Defines a CD track.
class CDTrackList
Represents a collection of CDTrack objects.
class DataDisc
The DataDisc interface provides methods for creating and burning data images to CD, DVD and Blu-ray Discs.
class DataDiscCallback
The DataDiscCallback interface lets you receive notifications about the burning progress.
class DataFile
Defines one file or directory in a data image.
class DataFileCallback
Implement this interface to handle DataFile signals.
class DataFileList
Represents a collection of DataFile objects.
class Device
The Device interface provides methods for working with CD, DVD and Blu-ray Disc (BD) devices.
class DeviceCallback
The DeviceCallback interface lets you receive progress notifications for long read operations like cue sheet reading, progress notifications for erase and format operations and progress notifications for lead-in/lead-out recording.
class DeviceEnum
Provides methods for enumerating and creating Device objects.
class DiscArchive
DiscArchive object provides a way for constructing large file trees and scheduling them for burning over multiple discs.
class DiscArchiveCallback
Implement this interface to receive progress notifications from DiscArchive.
class DiscArchiveFooterPolicy
Implement this interface to provide information to DiscArchive for managing the footer size.
class DiscCopy
Copies CD and DVD discs.
class DiscCopyCallback
Implement this callback interface to receive progress and status notifications from DiscCopy.
class DiscInfo
Disc Information.
class DiscLayout
Provides a way for recording all or a portion of DiscArchive content on a single disc.
class DiscLayoutCallback
Implement this interface to provide information to DiscArchive for managing the footer size.
class DVDFeatures
Container for the DVD features supported by the device.
class DVDMediaInfo
Container for DVD media information.
class DVDMinusMediaInfo
Container for DVD-R and DVD-RW media information.
class DVDPlusMediaInfo
Container for DVD+R and DVD+RW media information.
class Engine
PrimoBurner Engine.
class EngineCallback
Implement this interface to receive device/media change notifications from Engine interface.
class ErrorInfo
Describes a PrimoBurner error.
class IsoVolumeProps
Provides an interface for setting the properties of ISO volumes.
class JolietVolumeProps
Provides an interface for setting the properties of Joliet volumes.
class MediaInfo
The MediaInfo class provides extended information about the disc that is inserted in CD/DVD burner device.
struct Mode2FormedSubheader
Mode 2 Formed (Form1 or Form2) Sub-header structure.
class PcmAudioFormat
Specifies the PCM format of an audio input.
class QSubChannel
The QSubChannel class defines the information that can be stored in a Q sub-channel.
class QSubChannelIsrc
The QSubChannelIsrc structure defines the Track International Standard Recording Code data.
class QSubChannelMcn
The QSubChannelMcn structure defines the response data structure for the Media Catalog Number (MCN).
class QSubChannelPosition
The QSubChannelPosition structure defines the response data structure for the CD current position data (i.e., track, index, absolute address, relative address).
class RawToc
Raw Table Of Content (TOC)
class RawTocTrack
A Track from the Raw TOC (Raw Table Of Content)
class RawTocTrackEnum
Defines a collection of tracks from the Raw TOC.
class SessionInfo
Session Info.
class SpeedDescriptor
Speed Descriptor.
class SpeedEnum
Defines a collection of speed descriptors.
class Toc
Table Of Content (TOC)
class TocTrack
A Track from Table Of Content (TOC)
class TocTrackEnum
Defines a collection of tracks from the TOC.
class TrackBuffer
Represents a track buffer - used for reading data from audio and data tracks.
class TrackInfo
Track Information Structure.
class TrackInfoEx
Extended Track Information.
class UdfExtent
Defines a UDF file extent.
class UdfExtentList
Represents a collection of UdfExtent objects.
class UdfFileProps
Provides an interface for setting various properties of UDF file and directory items.
class UdfVolumeProps
Provides an interface for setting the properties of UDF volumes.
class VideoDVD
VideoDVD provides methods for creating DVD Video compatible image layouts.
Namespaces
primo
Top namespace for all libraries developed by Primo Software Corp.
primo::burner
PrimoBurner(tm) Application Programming Interface.
primo::burner::AudioCDError
AudioCD error codes.
primo::burner::AudioCDStatus
Status codes used in the AudioCDCallback::onWriteStatus and AudioCDCallback::onReadStatus methods.
primo::burner::AudioDecodingMethod
Audio Decoding Method.
primo::burner::AudioStorage
Specifies the possible audio storages used by AudioCD when writing to or reading from CD.
primo::burner::BDFormatSubType
Blu-ray Media Format Subtypes.
primo::burner::BDFormatType
Blu-ray Media Format Types.
primo::burner::BgFormatStatus
Background Format Status Codes.
primo::burner::BlockDeviceError
BlockDevice error codes.
primo::burner::BlockDeviceOpenFlags
Flags used with the BlockDevice::Open method.
primo::burner::BlockSize
Defines constants for media block sizes.
primo::burner::BootEmulation
Boot Emulation Type.
primo::burner::BootPlatformID
Boot PlatformID.
primo::burner::BufferSize
Defines constants for buffer sizes in blocks.
primo::burner::CDCopyReadMethod
Defines the DiscCopy read methods.
primo::burner::CDCopyWriteMethod
Defines DiscCopy write methods.
primo::burner::CDPregap
Defines constants for the CD pre-gap start and length.
primo::burner::CDTextCodePage
CD-TEXT Code Page Identifiers.
primo::burner::CDTextGenreCode
CD-TEXT Genre Codes.
primo::burner::CDTextLanguage
CD-TEXT Language Identifiers.
primo::burner::CDTextType
CD-TEXT Attribute Types.
primo::burner::DataDiscError
DataDisc error codes.
primo::burner::DataDiscStatus
DataDisc status codes.
primo::burner::DataOverwrite
Data Overwrite Flags.
primo::burner::DataSource
Defines the possible data sources of file data used by DataDisc during the ISO/Joliet/UDF image creation.
primo::burner::DataWriteStrategy
Data Write Strategy.
primo::burner::DeviceEnumError
DeviceEnum Error Codes.
primo::burner::DeviceError
Device error codes.
primo::burner::DiscArchiveError
DiscArchive error codes.
primo::burner::DiscCopyError
DiscCopy error codes.
primo::burner::DiscCopyStatus
DiscCopy status codes.
primo::burner::DiscLayoutError
DiscLayout error codes.
primo::burner::DiscStatus
The MSF structure allows you to translate blocks to minute, second and frame (MSF) interval This structure should not be used to calculate the Logical Block Address.
primo::burner::EngineError
Engine Error Codes.
primo::burner::EraseType
Erase Types.
primo::burner::ErrorFacility
Describes the PrimoBurner facilities that could generate errors.
primo::burner::FormatType
The FormatType::Enum enumeration defines the format types that can be used with the Device::format method.
primo::burner::GenericError
Generic error codes.
primo::burner::ImageConstraintFlags
Defines the constraints that can be applied during the image layout generation.
primo::burner::ImageTypeFlags
Defines constants for various image (filesystem) types.
primo::burner::LayerJumpRecordingStatus
Layer Jump Recording Status.
primo::burner::MediaProfile
Defines the media profiles that are returned from the Device::mediaProfile method.
primo::burner::MediaReady
Defines the medium ready status values returned by the Device::mediaState method.
primo::burner::MergeDirection
Defines data image layout merge direction.
primo::burner::Mode2BlockType
The Mode2BlockType::Enum enumeration defines the Mode2 block type.
primo::burner::QSubChannelFormat
Defines Q sub-channel formats.
primo::burner::QSubchannelInfoType
Defines the types of information encoded in the Q Sub-channel of a block.
primo::burner::RawPoint
Defines the raw toc point values.
primo::burner::RotationControlType
Medium Rotation Control.
primo::burner::SessionState
Session State.
primo::burner::SessionType
CD Session Type.
primo::burner::Speed1xKB
Defines constants for 1x speeds in Kbytes/s.
primo::burner::SubChannelFormat
Sub-channel formats returned by the Device::RawCDRead method.
primo::burner::TrackType
CD Track Types.
primo::burner::UdfAllocDescType
The UdfAllocDescType enumeration type defines allocation descriptor types that can be used in a UDF volume.
primo::burner::UdfPermissions
Defines UDF access permission constants.
primo::burner::UdfRevision
Defines the UDF (Universal Disc Format) versions that can be used in a UDF volume.
primo::burner::UdfTextEncoding
The UdfTextEncoding enumeration type defines text encodings that can be used in a UDF volume.
primo::burner::VideoDVDError
VideoDVD error codes.
primo::burner::VideoDVDValidation
The VideoDVDValidation enumeration defines the types of validation performed on a Video DVD layout.
primo::burner::WriteMethod
Write Method.
Enumerations
enum Enum {
Success = 0,
SystemWindows = 1,
SystemMacOSStatus = 2,
SystemMacMach = 3,
SystemPosix = 4,
Engine = 1000,
Device = 1001,
DeviceEnumerator = 1002,
DiscLayout = 1003,
DiscArchive = 1004,
AudioCD = 1005,
DataDisc = 1006,
BlockDevice = 1007,
DiscCopy = 1008,
VideoDVD = 1009
}
ErrorFacility::Enum.
enum Enum {
InformationNotSupplied = 0x00,
CurrentPosition = 0x01,
MediaCatalogNumber = 0x02,
Isrc = 0x03,
AdditionalInformation = 0x05
}
QSubchannelInfoType::Enum.
enum Enum {
EndOfRecord = 0x01,
Video = 0x02,
Audio = 0x04,
Data = 0x08,
Trigger = 0x10,
Form2 = 0x20,
RealTime = 0x40,
EndOfFile = 0x80
}
Mode2BlockType::Enum.
enum Enum {
System = 0x00,
ISO_8859_1 = 0x01
}
CDTextCodePage::Enum.
enum Enum {
Unknown = 0x00,
Albanian = 0x01,
Breton = 0x02,
Catalan = 0x03,
Croatian = 0x04,
Welsh = 0x05,
Czech = 0x06,
Danish = 0x07,
German = 0x08,
English = 0x09,
Spanish = 0x0A,
Esperanto = 0x0B,
Estonian = 0x0C,
Basque = 0x0D,
Faroese = 0x0E,
French = 0x0F,
Frisian = 0x10,
Irish = 0x11,
Gaelic = 0x12,
Galician = 0x13,
Icelandic = 0x14,
Italian = 0x15,
Lappish = 0x16,
Latin = 0x17,
Latvian = 0x18,
Luxembourgian = 0x19,
Lithuanian = 0x1A,
Hungarian = 0x1B,
Maltese = 0x1C,
Dutch = 0x1D,
Norwegian = 0x1E,
Occitan = 0x1F,
Polish = 0x20,
Portuguese = 0x21,
Romanian = 0x22,
Romansh = 0x23,
Serbian = 0x24,
Slovak = 0x25,
Slovenian = 0x26,
Finnish = 0x27,
Swedish = 0x28,
Turkish = 0x29,
Flemish = 0x2A,
Walloon = 0x2B,
Zulu = 0x45,
Vietnamese = 0x46,
Uzbek = 0x47,
Urdu = 0x48,
Ukrainian = 0x49,
Thai = 0x4A,
Telugu = 0x4B,
Tatar = 0x4C,
Tamil = 0x4D,
Tadzhik = 0x4E,
Swahili = 0x4F,
SrananTongo = 0x50,
Somali = 0x51,
Sinhalese = 0x52,
Shona = 0x53,
SerboCroatian = 0x54,
Ruthenian = 0x55,
Russian = 0x56,
Quechua = 0x57,
Pushtu = 0x58,
Punjabi = 0x59,
Persian = 0x5A,
Papamiento = 0x5B,
Oriya = 0x5C,
Nepali = 0x5D,
Ndebele = 0x5E,
Marathi = 0x5F,
Moldavian = 0x60,
Malaysian = 0x61,
Malagasay = 0x62,
Macedonian = 0x63,
Laotian = 0x64,
Korean = 0x65,
Khmer = 0x66,
Kazakh = 0x67,
Kannada = 0x68,
Japanese = 0x69,
Indonesian = 0x6A,
Hindi = 0x6B,
Hebrew = 0x6C,
Hausa = 0x6D,
Gurani = 0x6E,
Gujarati = 0x6F,
Greek = 0x70,
Georgian = 0x71,
Fulani = 0x72,
Dari = 0x73,
Churash = 0x74,
Chinese = 0x75,
Burmese = 0x76,
Bulgarian = 0x77,
Bengali = 0x78,
Belorussian = 0x79,
Bambora = 0x7A,
Azerbaijani = 0x7B,
Assamese = 0x7C,
Armenian = 0x7D,
Arabic = 0x7E,
Amharic = 0x7F
}
CDTextLanguage::Enum.
enum Enum {
Title = 0x80,
Performer = 0x81,
Songwriter = 0x82,
Composer = 0x83,
Arranger = 0x84,
Message = 0x85,
DiscId = 0x86,
Genre = 0x87,
UpcIsrc = 0x8E,
GenreText = 0x90
}
CDTextType::Enum.
enum Enum {
Unused = 0,
Undefined = 0x0001,
AdultContemp = 0x0002,
AltRock = 0x0003,
Childrens = 0x0004,
Classic = 0x0005,
ChristContemp = 0x0006,
Country = 0x0007,
Dance = 0x0008,
EasyListening = 0x0009,
Erotic = 0x000A,
Folk = 0x000B,
Gospel = 0x000C,
HipHop = 0x000D,
Jazz = 0x000E,
Latin = 0x000F,
Musical = 0x0010,
NewAge = 0x0011,
Opera = 0x0012,
Operetta = 0x0013,
Pop = 0x0014,
Rap = 0x0015,
Reggae = 0x0016,
Rock = 0x0017,
RhythmAndBlues = 0x0018,
SoundEffects = 0x0019,
Soundtrack = 0x001A,
SpokenWord = 0x001B,
WorldMusic = 0x001C,
Reserved = 0x001D,
Riaa = 32768
}
CDTextGenreCode::Enum.
enum Enum {
CDDA = 0,
CDRom = 1,
CDI = 2,
CDRomXA = 3,
Raw = 4
}
SessionType::Enum.
enum Enum {
Audio = 0,
Mode0 = 1,
Mode1 = 2,
Mode2Formless = 3,
Mode2Form1 = 4,
Mode2Form2 = 5,
Mode2Mixed = 6,
ModeRaw = 7,
Mode2Form1XA = 8,
Mode2Form1XARaw = 9,
Mode2Form2XA2352 = 10,
Error = 0xFF
}
TrackType::Enum.
enum Enum {
Empty = 0x00,
Open = 0x01,
Closed = 0x02
}
DiscStatus::Enum.
enum Enum {
Empty = 0x00,
Open = 0x01,
Damaged = 0x02,
Closed = 0x03
}
SessionState::Enum.
enum Enum {
NoLayerJump = 0x00,
Unspecified = 0x01,
ManualLayerJump = 0x02,
IntervalLayerJump = 0x03
}
MediaProfile::Enum.
enum Enum {
A0 = 0xA0,
A1 = 0xA1,
A2 = 0xA2,
B0 = 0xB0,
C0 = 0xC0
}
RawPoint::Enum.
enum Enum {
Disc = 0x00,
Minimal = 0x01,
LastTrack = 0x02,
UnreserveLastTrack = 0x03,
UncloseLastTrack = 0x04,
UncloseLastSession = 0x05,
LastSession = 0x06
}
EraseType::Enum.
enum Enum {
Present = 0,
NotPresent = 1,
StateUnknown = 2
}
MediaReady::Enum.
enum Enum {
Unknown = 0x0000,
Packet = 0x0001,
Tao = 0x0002,
Sao = 0x0004,
RawDao = 0x0008,
RawDao2352 = 0x0010,
FullRawDao = 0x0020,
DVDIncremental = 0x0040,
DVDDao = 0x0080,
DVDLayerJump = 0x0100,
BluRay = 0x0200
}
WriteMethod::Enum.
enum Enum {
None = 0x000,
PWDeinterleaved = 0x001,
PWRaw = 0x002
}
SubChannelFormat::Enum.
enum Enum {
CDMinusRWQuick = 0x0000,
DVDMinusRWQuick = 0x0001,
DVDMinusRWFull = 0x0002,
DVDMinusRWQuickGrowLastSession = 0x0004,
DVDMinusRWQuickAddSession = 0x0008,
DVDPlusRWFull = 0x0010,
DVDPlusRWRestart = 0x0020,
DVDPlusRWStop = 0x0040,
DVDRamFull = 0x0080,
DVDRamQuick = 0x0100
}
FormatType::Enum.
enum Enum {
NotFormatted = 0x00,
Partial = 0x01,
Pending = 0x02,
Completed = 0x03
}
BgFormatStatus::Enum.
enum Enum {
Unknown = 0xFFFF,
NoCurrentProfile = 0x0000,
CDRom = 0x0008,
CDR = 0x0009,
CDRW = 0x000A,
DVDRom = 0x0010,
DVDMinusRSeq = 0x0011,
DVDRam = 0x0012,
DVDMinusRWRO = 0x0013,
DVDMinusRWSeq = 0x0014,
DVDMinusRDLSeq = 0x0015,
DVDMinusRDLJump = 0x0016,
DVDPlusRW = 0x001A,
DVDPlusR = 0x001B,
DVDPlusRWDL = 0x002A,
DVDPlusRDL = 0x002B,
BDRom = 0x0040,
BDRSrm = 0x0041,
BDRSrmPow = 0xF041,
BDRRrm = 0x0042,
BDRE = 0x0043
}
MediaProfile::Enum.
enum Enum {
Unknown = 0x00,
Position = 0x01,
Mcn = 0x02,
Isrc = 0x03
}
QSubChannelFormat::Enum.
enum Enum {
Start = 0x01000000,
End = 0x01FFFFFF,
Success = primo::burner::GenericError::Success,
InternalError = primo::burner::GenericError::InternalError,
InvalidParameters = (DeviceError::Start + 1),
InvalidDeviceHandle = (DeviceError::Start + 2),
OSFeatureNotAvailable = (DeviceError::Start + 4),
NotDVDRW = (DeviceError::Start + 5),
InvalidFormatType = (DeviceError::Start + 6),
InvalidWriteMethod = (DeviceError::Start + 7),
WriteSpeedsNotAvailable = (DeviceError::Start + 9),
SingleOpenSession = (DeviceError::Start + 10),
NoActiveSession = (DeviceError::Start + 12),
InvalidQSubChannelCRC = (DeviceError::Start + 13),
InvalidCDSession = (DeviceError::Start + 14),
NotBDFormattable = (DeviceError::Start + 15),
NotEnoughFormattableCapacity = (DeviceError::Start + 16)
}
DeviceError::Enum.
enum Enum {
ConstantLinearVelocity = 0,
ConstantAngularVelocity = 1
}
RotationControlType::Enum.
enum Enum { BDFull = 0x00 }
BDFormatType::Enum.
enum Enum {
BDRSrmPow = 0x00,
BDRSrmNoPow = 0x01,
BDREQuickReformat = 0x100,
BDRENoCert = 0x101,
BDREFullCert = 0x102,
BDREQuickCert = 0x103
}
BDFormatSubType::Enum.
enum Enum {
DiscEnumErrorBase = 0x02000000,
DiscEnumErrorBaseEnd = 0x02FFFFFF,
Success = GenericError::Success,
SharingViolation = (DiscEnumErrorBase + 1),
InvalidIndex = (DiscEnumErrorBase + 2)
}
DeviceEnumError::Enum.
enum Enum {
EngineErrorBase = 0x08000000,
EngineErrorBaseEnd = 0x08FFFFFF,
Success = GenericError::Success,
InternalError = GenericError::InternalError,
NotInitialized = (EngineErrorBase + 1)
}
EngineError::Enum.
enum Enum {
None = 0,
Joliet = 1,
Iso9660 = 2,
Udf = 4,
UdfIso = Udf | Iso9660,
UdfJoliet = Udf | Joliet
}
ImageTypeFlags::Enum.
enum Enum {
File = 0,
Stream = 1,
Disc = 2,
ZeroPad = 3,
DiscImage = 4
}
DataSource::Enum.
enum Enum {
Left = 0,
Right = 1
}
MergeDirection::Enum.
enum Enum {
Other_Exec = 0x0001,
Other_Write = 0x0002,
Other_Read = 0x0004,
Other_ChAttr = 0x0008,
Other_Delete = 0x0010,
Group_Exec = 0x0020,
Group_Write = 0x0040,
Group_Read = 0x0080,
Group_ChAttr = 0x0100,
Group_Delete = 0x0200,
Owner_Exec = 0x0400,
Owner_Write = 0x0800,
Owner_Read = 0x1000,
Owner_ChAttr = 0x2000,
Owner_Delete = 0x4000,
ReadFile = Owner_Read | Group_Read | Other_Read,
ReadDir = Owner_Read | Group_Read | Other_Read | Owner_Exec | Group_Exec | Other_Exec,
All = 0x7FFF
}
UdfPermissions::Enum.
enum Enum {
BuildingFileSystem = 0,
WritingFileSystem = 1,
WritingImage = 2,
CachingSmallFiles = 3,
CachingNetworkFiles = 4,
CachingCDRomFiles = 5,
Initializing = 6,
Writing = 7,
WritingLeadOut = 8,
LoadingImageLayout = 9
}
DataDiscStatus::Enum.
enum Enum {
Start = 0x03000000,
End = 0x03FFFFFF,
Success = GenericError::Success,
InternalError = GenericError::InternalError,
InvalidParameters = (DataDiscError::Start + 1),
DeviceNotSet = (DataDiscError::Start + 3),
BadImageFile = (DataDiscError::Start + 6),
BufferUnderrun = (DataDiscError::Start + 7),
LayoutNotSet = (DataDiscError::Start + 8),
Interrupted = (DataDiscError::Start + 9),
Iso9660NotSupported = (DataDiscError::Start + 11),
JolietNotSupported = (DataDiscError::Start + 12),
Iso9660Level1NotSupported = (DataDiscError::Start + 13),
Checksum = (DataDiscError::Start + 16),
InvalidStructure = (DataDiscError::Start + 17),
InvalidDataSource = (DataDiscError::Start + 18),
DataStreamOpen = (DataDiscError::Start + 19),
IncompatibleMedia = (DataDiscError::Start + 23),
DataStreamRead = (DataDiscError::Start + 24),
CannotLoadImageLayout = (DataDiscError::Start + 25),
FileTooBig = (DataDiscError::Start + 26),
MediumNotPresent = (DataDiscError::Start + 27),
InvalidImageType = (DataDiscError::Start + 28),
IO = (DataDiscError::Start + 29),
InvalidWriteMethod = (DataDiscError::Start + 30),
UdfNotSupported = (DataDiscError::Start + 32),
EmptyFilename = (DataDiscError::Start + 33),
DuplicateFilename = (DataDiscError::Start + 34),
OutOfSpace = (DataDiscError::Start + 35)
}
DataDiscError::Enum.
enum Enum {
None = 0,
IsoLength8p3 = 1,
IsoLength31 = 2,
IsoLength212 = 4,
IsoTreeDepth = 8,
IsoText = 16,
JolietLength64 = 64,
IsoLevel1 = IsoTreeDepth | IsoLength8p3,
IsoLevel2 = IsoTreeDepth | IsoLength31,
IsoLongLevel2 = IsoTreeDepth | IsoLength212,
IsoStrictLevel1 = IsoText | IsoTreeDepth | IsoLength8p3,
IsoStrictLevel2 = IsoText | IsoTreeDepth | IsoLength31,
IsoStrictLongLevel2 = IsoText | IsoTreeDepth | IsoLength212,
JolietStandard = JolietLength64
}
ImageConstraintFlags.
enum Enum {
NoEmulation = 0,
Diskette120 = 1,
Diskette144 = 2,
Diskette288 = 3,
HardDisk = 4
}
BootEmulation::Enum.
enum Enum {
x86 = 0,
PowerPC = 1,
Mac = 2,
EFI = 0xEF
}
BootPlatformID::Enum.
enum Enum {
None = 0,
ReserveFileTableTrack = 1,
WriteFileTableTrack = 2
}
DataWriteStrategy::Enum.
enum Enum {
None = 0,
Overwrite = 1
}
DataOverwrite::Enum.
enum Enum {
Ansi = 8,
Utf16 = 16
}
UdfTextEncoding::Enum.
enum Enum {
Short = 1,
Long = 2
}
UdfAllocDescType::Enum.
enum Enum {
Revision102 = 0x0102,
Revision150 = 0x0150,
Revision200 = 0x0200,
Revision201 = 0x0201,
Revision250 = 0x0250,
Revision260 = 0x0260
}
UdfRevision::Enum.
enum Enum {
Memory = 0,
Tempfile = 1
}
AudioDecodingMethod::Enum.
enum Enum {
Initializing = 0,
InitializingDevice = 2,
DecodingAudio = 3,
Writing = 4,
WritingLeadOut = 5,
Reading = 6
}
AudioCDStatus::Enum.
enum Enum {
Start = 0x04000000,
End = 0x04FFFFFF,
Success = GenericError::Success,
InternalError = GenericError::InternalError,
InvalidParameters = (AudioCDError::Start + 1),
DeviceNotSet = (AudioCDError::Start + 3),
NoInput = (AudioCDError::Start + 4),
OutOfSpace = (AudioCDError::Start + 5),
Interrupted = (AudioCDError::Start + 6),
InputError = (AudioCDError::Start + 7),
InvalidCDSession = (AudioCDError::Start + 8),
InvalidTrack = (AudioCDError::Start + 9),
InvalidLba = (AudioCDError::Start + 10),
OutputError = (AudioCDError::Start + 11)
}
AudioCDError::Enum.
enum Enum {
File = 0,
Stream = 1
}
AudioStorage::Enum.
enum Enum {
Start = 0x07000000,
End = 0x07FFFFFF,
Success = GenericError::Success,
VideoTsIfoAccess = (VideoDVDError::Start + 1),
VideoTsIfoSize = (VideoDVDError::Start + 2),
VideoTsVobAccess = (VideoDVDError::Start + 3),
VtsIfoAccess = (VideoDVDError::Start + 5),
VtsIfoSize = (VideoDVDError::Start + 6),
VtsVobAccess = (VideoDVDError::Start + 7),
VtsVobSize = (VideoDVDError::Start + 8),
VtsIfoCorrupted = (VideoDVDError::Start + 9),
InvalidVtsSearchPointer = (VideoDVDError::Start + 10),
VideoTsVobNotFound = (VideoDVDError::Start + 11),
VideoTsVobNotExpected = (VideoDVDError::Start + 12),
VideoTsVobIfoIncorrectSize = (VideoDVDError::Start + 13)
}
VideoDVDError::ENum.
enum Enum {
Minimal = 0,
Full = 0xFFFFFFFF
}
VideoDVDValidation::Enum.
enum Enum {
Start = 0x05000000,
End = 0x05FFFFFF,
Success = GenericError::Success,
InternalError = GenericError::InternalError,
DeviceNotSet = (BlockDeviceError::Start + 2),
MediumNotPresent = (BlockDeviceError::Start + 3),
InvalidParameters = (BlockDeviceError::Start + 4),
InvalidBlockSize = (BlockDeviceError::Start + 5),
CommandSequence = (BlockDeviceError::Start + 6),
IncompatibleMedia = (BlockDeviceError::Start + 7),
InvalidFilenameLength = (BlockDeviceError::Start + 8),
InvalidDataSource = (BlockDeviceError::Start + 9)
}
BlockDeviceError::Enum.
enum Enum {
Read = 0x01,
Write = 0x02,
Format = 0x04
}
BlockDeviceOpenFlags::Enum.
enum Enum {
Start = 0x09000000,
End = 0x09FFFFFF,
Success = GenericError::Success,
InternalError = GenericError::InternalError,
MediumNotPresent = (DiscCopyError::Start + 3),
InvalidParameters = (DiscCopyError::Start + 4),
IncompatibleMedia = (DiscCopyError::Start + 5),
Interrupted = (DiscCopyError::Start + 6),
DestinationDiscIsNotBlank = (DiscCopyError::Start + 7),
SourceDiscIsBlank = (DiscCopyError::Start + 8),
InvalidImage = (DiscCopyError::Start + 9),
SourceDiscIsCopyProtected = (DiscCopyError::Start + 10),
SourceDiscLastSessionOpen = (DiscCopyError::Start + 11),
DestinationAndSourceCoincide = (DiscCopyError::Start + 12),
ImageFormatUnknown = (DiscCopyError::Start + 13),
TrackSizeUnknown = (DiscCopyError::Start + 14),
InvalidLayout = (DiscCopyError::Start + 15),
InvalidReadAddress = (DiscCopyError::Start + 16),
InvalidLayer0Size = (DiscCopyError::Start + 17),
InsufficientSpace = (DiscCopyError::Start + 18)
}
DiscCopyError::Enum.
enum Enum {
ReadingToc = 0,
ReadingData = 1,
WritingData = 2,
WritingLeadOut = 3
}
DiscCopyStatus::Enum.
enum Enum {
FullRaw = 1,
Raw2352 = 2
}
CDCopyReadMethod::Enum.
enum Enum {
FullRaw = 1,
Raw2352 = 2,
Raw = 3,
Cooked = 4
}
CDCopyWriteMethod::Enum.
enum Enum {
Start = 0x0B000000,
End = 0x0BFFFFFF,
Success = GenericError::Success,
InternalError = GenericError::InternalError,
InvalidParameters = (DiscLayoutError::Start + 1),
DeviceNotSet = (DiscLayoutError::Start + 2),
CommandSequence = (DiscLayoutError::Start + 3),
Interrupted = (DiscLayoutError::Start + 4),
IncompatibleMedia = (DiscLayoutError::Start + 5),
MediumNotPresent = (DiscLayoutError::Start + 6),
OutOfSpace = (DiscLayoutError::Start + 7),
FooterPrepareError = (DiscLayoutError::Start + 8),
FileReadError = (DiscLayoutError::Start + 9)
}
DiscLayoutError::Enum.
enum Enum {
Start = (0x0A000000),
End = (0x0AFFFFFF),
Success = GenericError::Success,
InternalError = GenericError::InternalError,
InvalidParameters = (DiscArchiveError::Start + 1),
DeviceNotSet = (DiscArchiveError::Start + 2),
MediumNotPresent = (DiscArchiveError::Start + 3),
IncompatibleMedia = (DiscArchiveError::Start + 4),
CannotLoadImageLayout = (DiscArchiveError::Start + 5),
NoNextDisc = (DiscArchiveError::Start + 6),
DiscFreeSpaceNotEnough = (DiscArchiveError::Start + 7),
FileMissing = (DiscArchiveError::Start + 8)
}
DiscArchiveError::Enum.
Functions
bool_t isAudioTrack (uint8_t CTL)
Determines whether a CD track is an audio track by its control field.
bool_t isDataTrack (uint8_t CTL)
Determines whether a CD track is a data track by its control field.
HPCDE_API
primo::burner::AudioCD
*PRIMOBURNER_CALL pb_create_audio_cd ()
Creates a new AudioCD instance.
HPCDE_API
primo::burner::AudioInput
*PRIMOBURNER_CALL pb_create_audio_input ()
Creates a new AudioInput instance.
HPCDE_API
primo::burner::AudioOutput
*PRIMOBURNER_CALL pb_create_audio_output ()
Creates a new AudioOutput instance.
HPCDE_API
primo::burner::BlockDevice
*PRIMOBURNER_CALL pb_create_block_device ()
Creates a new BlockDevice instance.
HPCDE_API
primo::burner::CDMode
*PRIMOBURNER_CALL pb_create_cd_mode ()
Creates a new CDMode instance.
HPCDE_API
primo::burner::CDSector
*PRIMOBURNER_CALL pb_create_cd_sector ()
Creates a new CDSector instance.
HPCDE_API
primo::burner::CDSession
*PRIMOBURNER_CALL pb_create_cd_session ()
Creates a new CDSession instance.
HPCDE_API
primo::burner::CDText
*PRIMOBURNER_CALL pb_create_cd_text ()
Creates a new CDText instance.
HPCDE_API
primo::burner::CDTrack
*PRIMOBURNER_CALL pb_create_cd_track ()
Creates a new CDTrack instance.
HPCDE_API
primo::burner::DataDisc
*PRIMOBURNER_CALL pb_create_data_disc ()
Creates a new DataDisc instance.
HPCDE_API
primo::burner::DataFile
*PRIMOBURNER_CALL pb_create_data_file ()
Creates a new DataFile instance.
HPCDE_API
primo::burner::DiscArchive
*PRIMOBURNER_CALL pb_create_disc_archive ()
Creates a new DiscArchive instance.
HPCDE_API
primo::burner::DiscCopy
*PRIMOBURNER_CALL pb_create_disc_copy ()
Creates a new DiscCopy instance.
HPCDE_API
primo::burner::Engine
*PRIMOBURNER_CALL pb_create_engine ()
Creates a new Engine instance.
HPCDE_API
primo::license::LicenseInfo
*PRIMOBURNER_CALL pb_create_license_info ()
Creates a new LicenseInfo instance.
HPCDE_API
primo::burner::PcmAudioFormat
*PRIMOBURNER_CALL pb_create_pcm_audio_format ()
Creates a new PcmAudioFormat instance.
HPCDE_API
primo::burner::RawTocTrack
*PRIMOBURNER_CALL pb_create_raw_toc_track ()
Creates a new RawTocTrack instance.
HPCDE_API
primo::burner::TrackBuffer
*PRIMOBURNER_CALL pb_create_track_buffer (int blockSize, uint32_t blocks=primo::burner::BufferSize::DefaultReadBufferBlocks)
Creates a new TrackBuffer instance.
HPCDE_API
primo::burner::UdfExtent
*PRIMOBURNER_CALL pb_create_udf_extent ()
Creates a new UdfExtent instance.
HPCDE_API
primo::burner::VideoDVD
*PRIMOBURNER_CALL pb_create_video_dvd ()
Creates a new VideoDVD instance.
HPCDE_API char PRIMOBURNER_CALL pb_device_index_to_drive_letter (int index)
The pb_device_index_to_drive_letter method retrieves the drive letter of a CD device from its index.
HPCDE_API void PRIMOBURNER_CALL pb_disable_trace_log ()
The pb_disable_trace_log method disables the PrimoBurner trace log.
HPCDE_API int PRIMOBURNER_CALL pb_drive_letter_to_device_index (char letter)
The pb_drive_letter_to_device_index method retrieves the index of a CD device from its drive letter.
HPCDE_API bool_t PRIMOBURNER_CALL pb_enable_trace_log (const char_t *filePath=NULL, bool_t useExisting=0)
The pb_enable_trace_log method enables the PrimoBurner trace log.
HPCDE_API int32_t PRIMOBURNER_CALL pb_set_license (const char *license)
Sets a license string.
Variables
static const int32_t BD = 2048
The size of a Blu-ray Disc (BD) block.
static const double BD = 4496.0
Defines the data transfer rate in Kbytes/s when burning or reading Blu-ray Disc at 1x, i.e.
static const double CD = 176.4
Defines the data transfer rate in Kbytes/s when burning or reading CDs at 1x, i.e.
static const int32_t CDDA = 2352
The size of an audio block.
static const int32_t CDRaw = BlockSize::CDDA + BlockSize::PWChannelSize
The size of a raw audio block.
static const int32_t CDRom = 2048
The size of a data block.
static const int32_t CDRomMode0 = 2336
The size of a CD-ROM Mode 0 data block.
static const int32_t CDRomMode2Form1 = 2336
The size of a CD-ROM Mode 2 Form1 data block.
static const int32_t CDRomMode2Form1XA = 2048
CD-ROM XA Block Size.
static const int32_t CDRomMode2Form1XARaw = 2056
CD-ROM RAW XA Block Size.
static const int32_t CDRomMode2Form2 = 2336
The size of a CD-ROM Mode 2 Form2 data block.
static const int32_t CDRomMode2Formless = 2336
The size of a CD-ROM Mode 2 Formless data block.
static const int32_t CDRomMode2Mixed = 2336
Same as BlockSize::CDRomMode2Form1 and BlockSize::CDRomMode2Form2.
static const int32_t DefaultReadBufferBlocks = 26
The default number of blocks allocated as data buffer for digital audio or data extraction (also known as CD ripping).
static const int32_t DVD = 2048
The size of a DVD block.
static const double DVD = 1385.0
Defines the data transfer rate in Kbytes/s when burning or reading DVDs at 1x, i.e.
static const int32_t InternalError = (GenericError::Start + 0x0FFFFFFF)
Internal error.
static const int32_t Length = 150
Default length of a CD track pre-gap.
static const int32_t PQChannelSize = 16
P-Q Channel Data Size.
static const int32_t PWChannelSize = 96
P-W Channel Data Size.
static const int32_t Start = (0)
This is not an actual error code.
static const int32_t Start = -150
Start address of the pre-gap before the first track on CD media, relative to the session start.
static const int32_t Success = (GenericError::Start + 0)
Success.
Function Documentation
HPCDE_API primo::burner::AudioCD* PRIMOBURNER_CALL pb_create_audio_cd ()
Creates a new AudioCD instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createAudioCD().
HPCDE_API primo::burner::AudioInput* PRIMOBURNER_CALL pb_create_audio_input ()
Creates a new AudioInput instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createAudioInput().
HPCDE_API primo::burner::AudioOutput* PRIMOBURNER_CALL pb_create_audio_output ()
Creates a new AudioOutput instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createAudioOutput().
HPCDE_API primo::burner::BlockDevice* PRIMOBURNER_CALL pb_create_block_device ()
Creates a new BlockDevice instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createBlockDevice().
HPCDE_API primo::burner::CDMode* PRIMOBURNER_CALL pb_create_cd_mode ()
Creates a new CDMode instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createCDMode().
HPCDE_API primo::burner::CDSector* PRIMOBURNER_CALL pb_create_cd_sector ()
Creates a new CDSector instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createCDSector().
HPCDE_API primo::burner::CDSession* PRIMOBURNER_CALL pb_create_cd_session ()
Creates a new CDSession instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createCDSession().
HPCDE_API primo::burner::CDText* PRIMOBURNER_CALL pb_create_cd_text ()
Creates a new CDText instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createCDText().
HPCDE_API primo::burner::CDTrack* PRIMOBURNER_CALL pb_create_cd_track ()
Creates a new CDTrack instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createCDTrack().
HPCDE_API primo::burner::DataDisc* PRIMOBURNER_CALL pb_create_data_disc ()
Creates a new DataDisc instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createDataDisc().
HPCDE_API primo::burner::DataFile* PRIMOBURNER_CALL pb_create_data_file ()
Creates a new DataFile instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createDataFile().
HPCDE_API primo::burner::DiscArchive* PRIMOBURNER_CALL pb_create_disc_archive ()
Creates a new DiscArchive instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createDiscArchive().
HPCDE_API primo::burner::DiscCopy* PRIMOBURNER_CALL pb_create_disc_copy ()
Creates a new DiscCopy instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createDiscCopy().
HPCDE_API primo::burner::Engine* PRIMOBURNER_CALL pb_create_engine ()
Creates a new Engine instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createEngine().
HPCDE_API primo::license::LicenseInfo* PRIMOBURNER_CALL pb_create_license_info ()
Creates a new LicenseInfo instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createLicenseInfo().
HPCDE_API primo::burner::PcmAudioFormat* PRIMOBURNER_CALL pb_create_pcm_audio_format ()
Creates a new PcmAudioFormat instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createPcmAudioFormat().
HPCDE_API primo::burner::RawTocTrack* PRIMOBURNER_CALL pb_create_raw_toc_track ()
Creates a new RawTocTrack instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createRawTocTrack().
HPCDE_API primo::burner::TrackBuffer* PRIMOBURNER_CALL pb_create_track_buffer (int blockSize, uint32_t blocks = primo::burner::BufferSize::DefaultReadBufferBlocks)
Creates a new TrackBuffer instance.
Parameters
blockSize The expected data block size in bytes. The actual size returned by the Device::readData method may differ depending on the data that was read from the disc. The actual size of the block is returned in the TrackBuffer::blockSize method during the reads through Device::readData and Device::readAudio.
blocks Number of audio or data blocks to be allocated. Each audio block is 2352 bytes and each data block is 2048 bytes.
Returns
A pointer to the created object.
See Also
TrackBuffer
Object Management
Referenced by primo::burner::Library::createTrackBuffer().
HPCDE_API primo::burner::UdfExtent* PRIMOBURNER_CALL pb_create_udf_extent ()
Creates a new UdfExtent instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createUdfExtent().
HPCDE_API primo::burner::VideoDVD* PRIMOBURNER_CALL pb_create_video_dvd ()
Creates a new VideoDVD instance.
Returns
A pointer to the created object.
See Also
Object Management
Referenced by primo::burner::Library::createVideoDVD().
HPCDE_API char PRIMOBURNER_CALL pb_device_index_to_drive_letter (int index)
The pb_device_index_to_drive_letter method retrieves the drive letter of a CD device from its index.
Parameters
index The index of the CD-ROM device
Returns
The drive letter of the CD-ROM device
Referenced by primo::burner::Library::deviceIndexToDriveLetter().
HPCDE_API int PRIMOBURNER_CALL pb_drive_letter_to_device_index (char letter)
The pb_drive_letter_to_device_index method retrieves the index of a CD device from its drive letter.
Parameters
letter The drive letter of the CD-ROM device
Returns
The index of the CD-ROM device
Referenced by primo::burner::Library::driveLetterToDeviceIndex().
HPCDE_API bool_t PRIMOBURNER_CALL pb_enable_trace_log (const char_t * filePath = NULL, bool_t useExisting = 0)
The pb_enable_trace_log method enables the PrimoBurner trace log.
The trace log is useful for identifying errors or problems with particular devices.
WARNING: This method will delete the file specified in filePath, if useExisting parameter is set to FALSE.
Parameters
filePath - full path to the file that should be used to log PrimoBurner trace messages. If set to NULL the method will create a log file named "PrimoBurner.log" in the user's home directory.
useExisting - indicates whether an existing file should be used or a new log file should be created. Set this parameter to FALSE to create a new empty log file or to TRUE to use an already existing file.
Returns
TRUE if the log was enabled successfully.
FALSE if useExisting was set to FALSE and a log file cannot be created with the specified path.
FALSE if useExisting was set to TRUE and a log file with the specified path does not exist.
Referenced by primo::burner::Library::enableTraceLog().
HPCDE_API int32_t PRIMOBURNER_CALL pb_set_license (const char * license)
Sets a license string.
Parameters
license A string with license information. It is allowed to set NULL in which case the license is cleared.
Returns
The current license status after the license is set.
Remarks
Until the current license is resolved pb_set_license will reject any license string and will return FALSE.
See Also
primo::license::LicenseStatusFlags
Referenced by primo::burner::Library::setLicense().