PrimoBurner(tm) for C++: primo::burner::Library Namespace Reference
primo::burner::Library Namespace Reference
This namespace contains global functions for the PrimoBurner library.
Functions
AudioCD * createAudioCD ()
Creates a new AudioCD object.
AudioInput * createAudioInput ()
Creates a new AudioInput object.
AudioOutput * createAudioOutput ()
Creates a new AudioOutput object.
BlockDevice * createBlockDevice ()
Creates a new BlockDevice object.
CDMode * createCDMode ()
Creates a new CDMode object.
CDSector * createCDSector ()
Creates a new CDSector object.
CDSession * createCDSession ()
Creates a new CDSession object.
CDText * createCDText ()
Creates a new CDText object.
CDTrack * createCDTrack ()
Creates a new CDTrack object.
DataDisc * createDataDisc ()
Creates a new DataDisc object.
DataFile * createDataFile ()
Creates a new DataFile object.
DiscArchive * createDiscArchive ()
Creates a new DiscArchive object.
DiscCopy * createDiscCopy ()
Creates a new DiscCopy object.
Engine * createEngine ()
Creates a new Engine object.
primo::license::LicenseInfo * createLicenseInfo ()
Creates a new LicenseInfo object.
PcmAudioFormat * createPcmAudioFormat ()
Creates a new PcmAudioFormat object.
RawTocTrack * createRawTocTrack ()
Creates a new RawTocTrack object.
TrackBuffer * createTrackBuffer (int blockSize, uint32_t blocks=primo::burner::BufferSize::DefaultReadBufferBlocks)
Creates a new TrackBuffer object.
UdfExtent * createUdfExtent ()
Creates a new UdfExtent object.
VideoDVD * createVideoDVD ()
Creates a new VideoDVD object.
char deviceIndexToDriveLetter (int index)
Gets drive letter from device index.
void disableTraceLog ()
Disables logging of PrimoBurner operations.
int driveLetterToDeviceIndex (char letter)
Gets device index from drive letter.
bool_t enableTraceLog (const char_t *filePath=NULL, bool_t useExisting=0)
Enables logging of PrimoBurner operations to file.
int32_t setLicense (const char *license)
Sets a license string.
Detailed Description
This namespace contains global functions for the PrimoBurner library.
These are the same functions that are exported from the library as pure "C" functions.
Function Documentation
AudioCD* primo::burner::Library::createAudioCD ()
Creates a new AudioCD object.
See pb_create_audio_cd.
Returns
A pointer to the new AudioCD object.
See Also
Object Management
References pb_create_audio_cd().
AudioInput* primo::burner::Library::createAudioInput ()
Creates a new AudioInput object.
See pb_create_audio_input.
Returns
A pointer to the new AudioInput object.
See Also
Object Management
References pb_create_audio_input().
AudioOutput* primo::burner::Library::createAudioOutput ()
Creates a new AudioOutput object.
See pb_create_audio_output.
Returns
A pointer to the new AudioOutput object.
See Also
Object Management
References pb_create_audio_output().
BlockDevice* primo::burner::Library::createBlockDevice ()
Creates a new BlockDevice object.
See pb_create_block_device.
Returns
A pointer to the new BlockDevice object.
See Also
Object Management
References pb_create_block_device().
CDMode* primo::burner::Library::createCDMode ()
Creates a new CDMode object.
See pb_create_cd_mode.
Returns
A pointer to the new CDMode object.
See Also
Object Management
References pb_create_cd_mode().
CDSector* primo::burner::Library::createCDSector ()
Creates a new CDSector object.
See pb_create_cd_sector.
Returns
A pointer to the new CDSector object.
See Also
Object Management
References pb_create_cd_sector().
CDSession* primo::burner::Library::createCDSession ()
Creates a new CDSession object.
See pb_create_cd_session.
Returns
A pointer to the new CDSession object.
See Also
Object Management
References pb_create_cd_session().
CDText* primo::burner::Library::createCDText ()
Creates a new CDText object.
See pb_create_cd_text.
Returns
A pointer to the new CDText object.
See Also
Object Management
References pb_create_cd_text().
CDTrack* primo::burner::Library::createCDTrack ()
Creates a new CDTrack object.
See pb_create_cd_track.
Returns
A pointer to the new CDTrack object.
See Also
Object Management
References pb_create_cd_track().
DataDisc* primo::burner::Library::createDataDisc ()
Creates a new DataDisc object.
See pb_create_data_disc.
Returns
A pointer to the new DataDisc object.
See Also
Object Management
References pb_create_data_disc().
DataFile* primo::burner::Library::createDataFile ()
Creates a new DataFile object.
See pb_create_data_file.
Returns
A pointer to the new DataFile object.
See Also
Object Management
References pb_create_data_file().
DiscArchive* primo::burner::Library::createDiscArchive ()
Creates a new DiscArchive object.
See pb_create_disc_archive.
Returns
A pointer to the new DiscArchive object.
See Also
Object Management
References pb_create_disc_archive().
DiscCopy* primo::burner::Library::createDiscCopy ()
Creates a new DiscCopy object.
See pb_create_disc_copy.
Returns
A pointer to the new DiscCopy object.
See Also
Object Management
References pb_create_disc_copy().
Engine* primo::burner::Library::createEngine ()
Creates a new Engine object.
See pb_create_engine.
Returns
A pointer to the new Engine object.
See Also
Object Management
References pb_create_engine().
primo::license::LicenseInfo* primo::burner::Library::createLicenseInfo ()
Creates a new LicenseInfo object.
See pb_create_license_info.
Returns
A pointer to the new LicenseInfo object.
See Also
Object Management
References pb_create_license_info().
PcmAudioFormat* primo::burner::Library::createPcmAudioFormat ()
Creates a new PcmAudioFormat object.
See pb_create_pcm_audio_format.
Returns
A pointer to the new PcmAudioFormat object.
See Also
Object Management
References pb_create_pcm_audio_format().
RawTocTrack* primo::burner::Library::createRawTocTrack ()
Creates a new RawTocTrack object.
See pb_create_raw_toc_track.
Returns
A pointer to the new RawTocTrack object.
See Also
Object Management
References pb_create_raw_toc_track().
TrackBuffer* primo::burner::Library::createTrackBuffer (int blockSize, uint32_t blocks = primo::burner::BufferSize::DefaultReadBufferBlocks)
Creates a new TrackBuffer object.
See pb_create_track_buffer.
Parameters
blockSize The expected data block size in bytes. The actual size returned by the Device::readData method may differ depending on the data that was read from the disc. The actual size of the block is returned in the TrackBuffer::blockSize method during the reads through Device::readData and Device::readAudio.
blocks Number of audio or data blocks to be allocated. Each audio block is 2352 bytes and each data block is 2048 bytes.
Returns
A pointer to the new TrackBuffer object.
See Also
Object Management
References pb_create_track_buffer().
UdfExtent* primo::burner::Library::createUdfExtent ()
Creates a new UdfExtent object.
See pb_create_udf_extent.
Returns
A pointer to the new UdfExtent object.
See Also
Object Management
References pb_create_udf_extent().
VideoDVD* primo::burner::Library::createVideoDVD ()
Creates a new VideoDVD object.
See pb_create_video_dvd.
Returns
A pointer to the new VideoDVD object.
See Also
Object Management
References pb_create_video_dvd().
char primo::burner::Library::deviceIndexToDriveLetter (int index)
Gets drive letter from device index.
See pb_device_index_to_drive_letter.
Parameters
index Device index
Returns
Drive letter
References pb_device_index_to_drive_letter().
void primo::burner::Library::disableTraceLog ()
Disables logging of PrimoBurner operations.
See pb_disable_trace_log.
References pb_disable_trace_log().
int primo::burner::Library::driveLetterToDeviceIndex (char letter)
Gets device index from drive letter.
See pb_drive_letter_to_device_index.
Parameters
letter Drive letter
Returns
Device index
References pb_drive_letter_to_device_index().
bool_t primo::burner::Library::enableTraceLog (const char_t * filePath = NULL, bool_t useExisting = 0)
Enables logging of PrimoBurner operations to file.
See pb_enable_trace_log.
Parameters
filePath The file path of the trace log.
useExisting Specifies whether to append to existing trace log or to create a new one.
Returns
TRUE if successful, FALSE otherwise.
References pb_enable_trace_log().
int32_t primo::burner::Library::setLicense (const char * license)
Sets a license string.
See pb_set_license.
Parameters
license A string with license information.
Returns
license status
References pb_set_license().